import jsPDF from "jspdf";

export const generateAIReport = ({
  bestCrop,
  weather,
  confidence,
  riskAnalysis,
  weatherAnalysis,
  cropAnalysis,
}) => {
  const doc = new jsPDF();

  let y = 20;

  const PAGE_HEIGHT = 270;

  const checkPageBreak = () => {
    if (y > PAGE_HEIGHT) {
      doc.addPage();
      y = 20;
    }
  };

  const addText = (text, x = 15, spacing = 8) => {
    checkPageBreak();

    const lines = doc.splitTextToSize(text, 180);

    doc.text(lines, x, y);

    y += lines.length * 7 + spacing;
  };

  const addSectionTitle = (title) => {
    y += 5;

    checkPageBreak();

    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235); // blue

    doc.text(title, 15, y);

    y += 10;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
  };

  // ======================
  // HEADER
  // ======================

  doc.setFillColor(22, 163, 74);

  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);

  doc.setFontSize(22);

  doc.text("AgriSense AI Report", 15, 20);

  y = 40;

  doc.setTextColor(0, 0, 0);

  // ======================
  // OVERVIEW
  // ======================

  addSectionTitle("Recommendation Overview");

  addText(`Generated: ${new Date().toLocaleString()}`);

  addText(`Recommended Crop: ${bestCrop?.crop || "N/A"}`);

  addText(
    `Expected Profit: Rs. ${bestCrop?.expected_profit?.toLocaleString() || 0}`,
  );

  addText(`AI Confidence: ${confidence}%`);

  // ======================
  // WEATHER
  // ======================

  addSectionTitle("Weather Analysis");

  addText(`Temperature: ${weather?.temperature}°C`);

  addText(`Humidity: ${weather?.humidity}%`);

  addText(`Weather Status: ${weatherAnalysis?.status}`);

  // ======================
  // RISK
  // ======================

  addSectionTitle("Risk Assessment");

  addText(`Risk Level: ${riskAnalysis?.level}`);

  addText(`Risk Score: ${riskAnalysis?.score}%`);

  // ======================
  // SWOT
  // ======================

  addSectionTitle("SWOT Analysis");

  // Strengths
  doc.setTextColor(22, 163, 74);

  addText("Strengths:");

  doc.setTextColor(0, 0, 0);

  cropAnalysis?.strengths?.forEach((item) => {
    addText(`• ${item}`);
  });

  // Weaknesses
  doc.setTextColor(220, 38, 38);

  addText("Weaknesses:");

  doc.setTextColor(0, 0, 0);

  cropAnalysis?.weaknesses?.forEach((item) => {
    addText(`• ${item}`);
  });

  // Opportunities
  doc.setTextColor(37, 99, 235);

  addText("Opportunities:");

  doc.setTextColor(0, 0, 0);

  cropAnalysis?.opportunities?.forEach((item) => {
    addText(`• ${item}`);
  });

  // Risks
  doc.setTextColor(234, 179, 8);

  addText("Risks:");

  doc.setTextColor(0, 0, 0);

  cropAnalysis?.risks?.forEach((item) => {
    addText(`• ${item}`);
  });

  // ======================
  // AI VERDICT
  // ======================

  addSectionTitle("AI Verdict");

  addText(
    `${bestCrop?.crop} is currently the most suitable crop based on expected profitability, weather compatibility, market demand, risk assessment, and overall AI suitability analysis.`,
  );

  // ======================
  // FOOTER
  // ======================

  const pageCount = doc.internal.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setFontSize(10);

    doc.setTextColor(120, 120, 120);

    doc.text(`Generated by AgriSense AI • Page ${i} of ${pageCount}`, 15, 290);
  }

  doc.save(`agrisense-${bestCrop?.crop || "report"}.pdf`);
};
