import jsPDF from "jspdf";

export const generateAIReport = ({
  bestCrop,
  weather,
  confidence,
  genaiInsights,
}) => {
  const doc = new jsPDF();

  let y = 20;
  const PAGE_HEIGHT = 270;

  const checkPageBreak = () => {
    if (y > PAGE_HEIGHT) {
      doc.addPage();
      y = 20;
    }
  };

  const addText = (text, x = 15, spacing = 8) => {
    checkPageBreak();

    const lines = doc.splitTextToSize(String(text || "N/A"), 180);

    doc.text(lines, x, y);

    y += lines.length * 7 + spacing;
  };

  const addSectionTitle = (title) => {
    y += 5;
    checkPageBreak();

    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text(title, 15, y);

    y += 10;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
  };

  const addList = (items = []) => {
    items.forEach((item) => addText(`• ${item}`));
  };

  doc.setFillColor(22, 163, 74);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("AgriSense AI Report", 15, 20);

  y = 40;
  doc.setTextColor(0, 0, 0);

  addSectionTitle("Recommendation Overview");
  addText(`Generated: ${new Date().toLocaleString()}`);
  addText(`Recommended Crop: ${bestCrop?.crop || "N/A"}`);
  addText(
    `Expected Profit: Rs. ${
      bestCrop?.expected_profit?.toLocaleString() || "N/A"
    }`,
  );

  if (confidence != null) {
    addText(`ML Confidence: ${confidence}%`);
  }

  addSectionTitle("AI Summary");
  addText(genaiInsights?.summary);

  addSectionTitle("AI Reasoning");
  addList(genaiInsights?.reasoning);

  addSectionTitle("Weather");
  addText(
    `Temperature: ${
      weather?.temperature != null ? `${weather.temperature}°C` : "N/A"
    }`,
  );
  addText(
    `Humidity: ${
      weather?.humidity != null ? `${weather.humidity}%` : "N/A"
    }`,
  );
  addText(`Condition: ${weather?.condition || "N/A"}`);

  addSectionTitle("Strengths");
  addList(genaiInsights?.strengths);

  addSectionTitle("Weaknesses");
  addList(genaiInsights?.weaknesses);

  addSectionTitle("Opportunities");
  addList(genaiInsights?.opportunities);

  addSectionTitle("Risks");
  addList(genaiInsights?.risks);

  addSectionTitle("Comparison");
  addList(genaiInsights?.comparison);

  addSectionTitle("Action Plan");
  addList(genaiInsights?.action_plan);

  addSectionTitle("AI Verdict");
  addText(genaiInsights?.verdict);

  const pageCount = doc.internal.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `Generated by AgriSense AI • Page ${i} of ${pageCount}`,
      15,
      290,
    );
  }

  doc.save(`agrisense-${bestCrop?.crop || "report"}.pdf`);
};