name: Deploy AgriSense

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "820381490998"
  ECS_CLUSTER: agrisense-cluster
  ECR_REGISTRY: 820381490998.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  deploy:
    name: Build and Deploy AgriSense
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::820381490998:role/AgriSenseGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push client
        run: |
          docker build \
            --build-arg VITE_API_URL=http://agrisense-alb-1672199196.ap-south-1.elb.amazonaws.com/api \
            -t $ECR_REGISTRY/agrisense-client:latest \
            ./client

          docker push \
            $ECR_REGISTRY/agrisense-client:latest

      - name: Build and push server
        run: |
          docker build \
            -t $ECR_REGISTRY/agrisense-server:latest \
            ./server

          docker push \
            $ECR_REGISTRY/agrisense-server:latest

      - name: Build and push ML service
        run: |
          docker build \
            -t $ECR_REGISTRY/agrisense-ml:latest \
            ./ml-service

          docker push \
            $ECR_REGISTRY/agrisense-ml:latest

      - name: Create GenAI Google credentials
        env:
          GOOGLE_AWS_CREDENTIALS: ${{ secrets.GOOGLE_AWS_CREDENTIALS }}
        run: |
          printf '%s' "$GOOGLE_AWS_CREDENTIALS" > genai-service/google-aws-credentials.json

      - name: Build and push GenAI service
        run: |
          docker build \
            -t $ECR_REGISTRY/agrisense-genai:latest \
            ./genai-service

          docker push \
            $ECR_REGISTRY/agrisense-genai:latest

      - name: Deploy Client
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service agrisense-client \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Deploy Server
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service agrisense-server \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Deploy ML
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service agrisense-ml \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Deploy GenAI
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service agrisense-genai \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Wait for ECS deployments
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services \
              agrisense-client \
              agrisense-server \
              agrisense-ml \
              agrisense-genai \
            --region $AWS_REGION